/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema.h"
#include "token.h"

extern char **resources_db;
extern int no_resources;
// users known by server
extern char **users_known;
extern int no_users_known;
// users databes
extern user_db *user_database;
// authz tokens with associated permissions
extern authz_token_permissions *authz_token_permissions_list;

token *
request_authorization_1_svc(request_authorization_param *argp, struct svc_req *rqstp)
{
	static token  result;

	/*
	 * insert server code here
	 */
	char *user_id = argp->user_id;
	int auto_refresh = argp->auto_refresh;

	if (auto_refresh) {
		printf("Begin %s AUTHZ REFRESH\n", user_id);
	} else {
		printf("Begin %s AUTHZ\n", user_id);
	}

	int user_found = 0;
	

	// check if user_id is one of the known users
	for (int i = 0; i < no_users_known; i++) {
		if (strncmp(users_known[i], user_id, strlen(users_known[i])) == 0) {
			user_found = 1;
		}
	}

	if (user_found == 0) {
		
		// create impossible values for token and # operations
		result.token_value = "USER_NOT_FOUND";
		result.no_available_operations = -1;
	} else {
		result.token_value = generate_access_token(user_id);
		result.no_available_operations = 0;
	}
	
	return &result;
}

approve_request_token_response *
approve_request_token_1_svc(token *argp, struct svc_req *rqstp)
{
	static approve_request_token_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

request_access_token_response *
request_access_token_1_svc(request_access_token_param *argp, struct svc_req *rqstp)
{
	static request_access_token_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

validate_delegated_action_response *
validate_delegated_action_1_svc(validate_delegated_action_param *argp, struct svc_req *rqstp)
{
	static validate_delegated_action_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}
