/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema.h"

#define BUFSIZE 100

// used for reading data into it
char buf[BUFSIZE];

request_access_token_response execute_request_client(char *user_id, int auto_refresh, CLIENT* clnt) {
	request_access_token_response response;
	request_authorization_param param;
	
	param.user_id = user_id;
	param.auto_refresh = auto_refresh;

	token *authz_token = request_authorization_1(&param, clnt);

	if (authz_token == NULL) {
		printf("USER_NOT_FOUND\n");
		memset(&response, 0, sizeof(response));
		return response;
	} else {
		printf("%s\n", authz_token->token_value);
	}

}

void execute_operation_client(char *host, char *filename_operations) {
	CLIENT *clnt;
	/*
	token  *result_1;
	request_authorization_param  request_authorization_1_arg;
	approve_request_token_response  *result_2;
	token  approve_request_token_1_arg;
	request_access_token_response  *result_3;
	request_access_token_param  request_access_token_1_arg;
	validate_delegated_action_response  *result_4;
	validate_delegated_action_param  validate_delegated_action_1_arg;
	*/

	#ifndef	DEBUG
		clnt = clnt_create (host, CHEKPROG, CHECKVERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */


	FILE *fp = fopen(filename_operations, "r");
	if (fp == NULL) {
		printf("Cannot open %s\n", filename_operations);
		exit(1);
	}

	const char delimiter[2] = ",";

	char *user_id;
	char *operation;
	char *option;

	while (fgets(buf, BUFSIZE, fp)) {
		user_id = strtok(buf, delimiter);
		operation = strtok(NULL, delimiter);
		option = strtok(NULL, delimiter);

		// printf("%s will do %s on %s", user_id, operation, option);

		if (strncmp(operation, "REQUEST", strlen(operation)) == 0) {
			// options represents auto_refresh
			int auto_refresh = atoi(option);

			execute_request_client(user_id, auto_refresh, clnt);
			// printf("auto_refresh: %d\n", auto_refresh);
		} else if ((strncmp(operation, "READ", strlen(operation)) == 0) ||
				   (strncmp(operation, "INSERT", strlen(operation)) == 0) ||
				   (strncmp(operation, "MODIFY", strlen(operation)) == 0) ||
				   (strncmp(operation, "DELETE", strlen(operation)) == 0) ||
				   (strncmp(operation, "EXECUTE", strlen(operation)) == 0)) {
			
			// option is the resource accesed so we let's remove the \n at the end of it
			// for all rows read from client.in except the last one
			if (option[strlen(option) - 1] == '\n') {
				option[strlen(option) - 1] = '\0';
			}

			// printf("option: %s\n", option);
		} else {
			printf("UNDEFINED BEHAVIOR for operation: %s\n", operation);
		}
	}

	#ifndef	DEBUG
	clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc !=  3) {
		printf ("usage: %s server_host <fisier_operatii> \n", argv[0]);
		exit (1);
	}

	host = argv[1];
	execute_operation_client(host, argv[2]);
exit (0);
}
