/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema.h"

extern char **resources_db;
extern int no_resources;
// users known by server
extern char **users_known;
extern int no_users_known;
// users databes
extern user_db *user_database;
// authz tokens with associated permissions
extern authz_token_permissions *authz_token_permissions_list;

token *
request_authorization_1_svc(request_authorization_param *argp, struct svc_req *rqstp)
{
	static token  result;


	printf("%s", resources_db[0]);
	/*
	 * insert server code here
	 */

	return &result;
}

approve_request_token_response *
approve_request_token_1_svc(token *argp, struct svc_req *rqstp)
{
	static approve_request_token_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

request_access_token_response *
request_access_token_1_svc(request_access_token_param *argp, struct svc_req *rqstp)
{
	static request_access_token_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

validate_delegated_action_response *
validate_delegated_action_1_svc(validate_delegated_action_param *argp, struct svc_req *rqstp)
{
	static validate_delegated_action_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}
